### Create new User
POST http://localhost/api/auth/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "username": "{{username}}"
}

### Log in as created User

POST http://localhost/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body.token); %}

### Create Team

POST http://localhost/api/teams
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "TestTeam"
}
