"""empty message

Revision ID: 017cb533cb90
Revises: 2d7701f1f80c
Create Date: 2024-11-22 13:12:24.398994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017cb533cb90'
down_revision = '2d7701f1f80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'User', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
