"""empty message

Revision ID: 1b98ea3857a4
Revises: cd5bf0fec2b0
Create Date: 2025-01-08 16:43:51.091518

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b98ea3857a4"
down_revision = "cd5bf0fec2b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Document", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    with op.batch_alter_table("DocumentEdit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )
    with op.batch_alter_table("Project", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )
    with op.batch_alter_table("Schema", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )
    with op.batch_alter_table("Team", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    op.bulk_insert(
        sa.table(
            "DocumentEditState",
            sa.column("id", sa.Integer),
            sa.column("type", sa.String),
        ),
        [
            {"id": 5, "type": "MENTION_SUGGESTION"},
            {"id": 6, "type": "RELATION_SUGGESTION"},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Team", schema=None) as batch_op:
        batch_op.drop_column("active")

    with op.batch_alter_table("Schema", schema=None) as batch_op:
        batch_op.drop_column("active")
        batch_op.drop_column("name")

    with op.batch_alter_table("Project", schema=None) as batch_op:
        batch_op.drop_column("active")

    with op.batch_alter_table("DocumentEdit", schema=None) as batch_op:
        batch_op.drop_column("active")

    with op.batch_alter_table("Document", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
