"""empty message

Revision ID: 96da1028ce56
Revises: 017cb533cb90
Create Date: 2024-11-29 21:02:20.522174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96da1028ce56'
down_revision = '017cb533cb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DocumentEdit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DocumentEdit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
