"""empty message

Revision ID: cd5bf0fec2b0
Revises: 225a57721908
Create Date: 2024-12-17 20:28:18.300601

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd5bf0fec2b0"
down_revision = "225a57721908"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("DocumentEdit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("schema_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "Schema", ["schema_id"], ["id"])

    with op.batch_alter_table("Schema", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "Team", ["team_id"], ["id"])

    with op.batch_alter_table("SchemaMention", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entityPossible", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("color", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    with op.batch_alter_table("SchemaRelation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    with op.batch_alter_table("Token", schema=None) as batch_op:
        batch_op.drop_column("bio_tag")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Token", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("bio_tag", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("SchemaRelation", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("SchemaMention", schema=None) as batch_op:
        batch_op.drop_column("description")
        batch_op.drop_column("color")
        batch_op.drop_column("entityPossible")

    with op.batch_alter_table("Schema", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    with op.batch_alter_table("DocumentEdit", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("schema_id")

    # ### end Alembic commands ###
