"""empty message

Revision ID: d4fcb76a0847
Revises: 1b98ea3857a4
Create Date: 2025-01-16 15:03:15.258700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fcb76a0847'
down_revision = '1b98ea3857a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Mention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_mention_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'SchemaMention', ['schema_mention_id'], ['id'])
        batch_op.drop_column('tag')

    with op.batch_alter_table('Relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_relation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'SchemaRelation', ['schema_relation_id'], ['id'])
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schema_relation_id')

    with op.batch_alter_table('Mention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schema_mention_id')

    # ### end Alembic commands ###
